namespace Copaste
{
    using System.Collections.Generic;

    internal static class Localization
    {
        internal static Dictionary<string, string> BuildEnglish(CopasteSettings settings)
        {
            return new Dictionary<string, string>
            {
                { settings.GetSettingsLocaleID(), "Copaste" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ToggleBinding)), "Toggle Copaste tool" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ToggleBinding)), "Activates/deactivates the Copaste selection tool." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.CopyBinding)), "Copy selection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.CopyBinding)), "Copies the selected props to the clipboard (while the tool is active)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PasteBinding)), "Paste" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PasteBinding)), "Enters paste mode with a preview following the mouse (while the tool is active)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.DeleteBinding)), "Delete selection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.DeleteBinding)), "Deletes the selected props (while the tool is active)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RaiseBinding)), "Raise selection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RaiseBinding)), "Raises the selected props (or the paste preview) while held." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.LowerBinding)), "Lower selection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.LowerBinding)), "Lowers the selected props (or the paste preview) while held." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.UndoBinding)), "Undo" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RedoBinding)), "Redo" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RedoBinding)), "Redoes the last undone Copaste action (move, rotate, align, height, nudge, delete, paste, relocate)." },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.UndoBinding)), "Undoes the last Copaste action (move, rotate, align, height, nudge, delete, paste, relocate)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RelocateBinding)), "Relocate building" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RelocateBinding)), "Starts Relocate for the selected building (exactly one finished building selected). Press again or right-click to cancel." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Select same" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Toggles a type filter taken from the hovered/selected prop: while active, marquee selection only picks props of that type. Press again to clear." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Snap to ground" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Drops the selection back onto the terrain (resets height)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Match height" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Arms height picking: the next prop you click sets the height for the whole selection." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kMatchHeightAction), "Match height" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Nudge away" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Nudges the selection away from the camera." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Nudge towards" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Nudges the selection towards the camera." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Nudge left" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Nudges the selection to the left." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Nudge right" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Nudges the selection to the right." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Align gap +" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Increases the gap of the last align (Line, To prop or Circle) by 0.5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Align gap -" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Decreases the gap of the last align (Line, To prop or Circle) by 0.5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ModLanguage)), "Mod language" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ModLanguage)), "Language for the Copaste panel and these options only — the game keeps its own language." },
                { settings.GetEnumValueLocaleID(ModLanguageOption.Auto), "Auto (game language)" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.English), "English" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.German), "Deutsch" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.French), "Français" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.Serbian), "Srpski" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Ignore placement errors when pasting" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AnarchyPaste)), "The paste stamp ignores the game's placement errors (overlaps, collisions), so it goes down anywhere. Pasting only. With the Anarchy mod installed, pasted props and fences also receive its override protection; buildings do not, and neither does Relocate — moving a building into another can still make the game remove one." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PanelTheme)), "Panel theme" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PanelTheme)), "How the Copaste panel looks: the mod's own style, or the game's colors and panels (vanilla)." },
                { settings.GetEnumValueLocaleID(PanelThemeOption.Copaste), "Copaste" },
                { settings.GetEnumValueLocaleID(PanelThemeOption.Vanilla), "Vanilla (game style)" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PanelScale)), "Panel size (%)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PanelScale)), "Scales the whole Copaste panel, text included — for anyone who finds the default too small." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.TextScale)), "Text size (%)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.TextScale)), "Enlarges only the text on the Copaste panel — the panel itself keeps its size." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MaxSelection)), "Selection limit" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MaxSelection)), "Maximum number of objects in one selection. Higher values can strain the game during large operations — raise it only if your machine keeps up." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MaxOverlayShapes)), "Selection outline limit" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MaxOverlayShapes)), "Maximum number of selection outlines (circles and fence lines) drawn at once. Purely visual — objects beyond the limit stay selected." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectionListMax)), "Selected props list limit" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectionListMax)), "Largest selection that still shows the per-prop list in the panel. Long lists cost a little performance while the panel is open." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kToggleAction), "Toggle Copaste tool" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kCopyAction), "Copy selection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kPasteAction), "Paste" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kDeleteAction), "Delete selection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRaiseAction), "Raise selection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kLowerAction), "Lower selection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kUndoAction), "Undo" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRedoAction), "Redo" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRelocateAction), "Relocate building" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSelectSameAction), "Select same" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSnapGroundAction), "Snap to ground" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeUpAction), "Nudge away" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeDownAction), "Nudge towards" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeLeftAction), "Nudge left" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeRightAction), "Nudge right" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapPlusAction), "Align gap +" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapMinusAction), "Align gap -" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kGeneralTab), "General" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kKeybindingsTab), "Key bindings" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kBehaviorGroup), "Behavior" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kPanelGroup), "Panel" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kLimitsGroup), "Limits" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kToolGroup), "Tool" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kClipboardGroup), "Clipboard" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kEditingGroup), "Editing" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kNudgeGroup), "Nudge" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kAlignGroup), "Align" },
                { settings.GetBindingMapLocaleID(), "Copaste" },

                // Panel (cohtml) — ključevi koje mjs čita kroz cs2/l10n.
                { "COPASTE.STAT_SELECTED", "Selected" },
                { "COPASTE.STAT_CLIPBOARD", "Clipboard" },
                { "COPASTE.CLEAR", "Clear" },
                { "COPASTE.CLEAR_TIP", "Clear the clipboard" },
                { "COPASTE.PROP_LABEL", "Prop" },
                { "COPASTE.FILTER", "Filter" },
                { "COPASTE.FILTER_OFF", "Off" },
                { "COPASTE.FILTER_TIP", "Marquee prop filter: box select only picks this prop type. Click a prop to set it, click again to turn off (T)" },
                { "COPASTE.SEC_SELECTION", "Selection" },
                { "COPASTE.CHIP_SOLO_TIP", "Right click: just this one / everything" },
                { "COPASTE.CHIP_PROPS", "Props" },
                { "COPASTE.CHIP_PROPS_TIP", "Benches, lamps and other props" },
                { "COPASTE.CHIP_TREES", "Trees" },
                { "COPASTE.CHIP_TREES_TIP", "Trees, bushes and other vegetation" },
                { "COPASTE.CHIP_DECALS", "Decals" },
                { "COPASTE.CHIP_DECALS_TIP", "Road markings, stains and other decals" },
                { "COPASTE.CHIP_SURFACES", "Surfaces" },
                { "COPASTE.CHIP_SURFACES_TIP", "Painted surfaces" },
                { "COPASTE.CHIP_BUILDINGS", "Buildings" },
                { "COPASTE.CHIP_BUILDINGS_TIP", "Service buildings, unique ones and grown homes" },
                { "COPASTE.CHIP_FENCES", "Fences" },
                { "COPASTE.CHIP_FENCES_TIP", "Fences and hedges drawn along a line" },
                { "COPASTE.CHIP_NETWORKS", "Networks" },
                { "COPASTE.CHIP_NETWORKS_TIP", "Road, path and track nodes and segments — move, rotate, copy and delete; power lines and pipes stay untouched" },
                { "COPASTE.SEC_BUILDING_ELEMENTS", "Building elements" },
                { "COPASTE.BUILDING_ELEMENTS_TIP", "When on, selection also reaches elements that belong to buildings — their props, trees, decals and lot surfaces, each following its filter above. Deleting a lot decoration surface also removes what it keeps spawning. When off, nothing building-owned can be selected, not even by click" },
                { "COPASTE.ON", "On" },
                { "COPASTE.OFF", "Off" },
                { "COPASTE.SEC_SELECTED_PROPS", "Selected props" },
                { "COPASTE.SEC_CLIPBOARD", "Clipboard" },
                { "COPASTE.COPY", "Copy" },
                { "COPASTE.COPY_TIP", "Copy selection (Ctrl+C)" },
                { "COPASTE.PASTE", "Paste" },
                { "COPASTE.PASTE_TIP", "Paste mode on/off (Ctrl+V)" },
                { "COPASTE.SAVE", "Save" },
                { "COPASTE.SAVE_TIP", "Save selection as blueprint" },
                { "COPASTE.SEC_PASTE_LOOK", "Paste look" },
                { "COPASTE.PASTE_LOOK_TIP", "Original: pasted props keep the copied prop's color variation. Random: the game picks one" },
                { "COPASTE.ORIGINAL", "Original" },
                { "COPASTE.RANDOM", "Random" },
                { "COPASTE.UNDERGROUND_TIP", "Underground view: pick and box-select only what is below ground (metro, tunnels). Copy/paste and undo work the same in both worlds (U)" },
                { "COPASTE.SEC_ROAD_SNAP", "Road snap" },
                { "COPASTE.ROAD_SNAP_TIP", "Pasted buildings snap to the nearest road like normal plopping — the whole group rotates to face it. While snapped, rotation follows the road" },
                { "COPASTE.SEC_EDIT", "Edit" },
                { "COPASTE.UNDO", "Undo" },
                { "COPASTE.UNDO_TIP", "Undo last action (Ctrl+Z)" },
                { "COPASTE.REDO", "Redo" },
                { "COPASTE.REDO_TIP", "Redo the last undone action (Ctrl+Y)" },
                { "COPASTE.RELOCATE", "Relocate" },
                { "COPASTE.RELOCATE_TIP", "Move the selected building (Tab): it follows the cursor, road snap sets the facing. Click to place, Tab or right click to cancel. To rotate freely, place it first and use RMB drag" },
                { "COPASTE.DELETE", "Delete" },
                { "COPASTE.DELETE_TIP", "Delete selection (Del)" },
                { "COPASTE.SEC_ALIGN", "Align" },
                { "COPASTE.GROUND", "Ground" },
                { "COPASTE.GROUND_TIP", "Snap selection to terrain (End)" },
                { "COPASTE.MATCHH", "Match H" },
                { "COPASTE.MATCHH_TIP", "Pick height from a prop (Home)" },
                { "COPASTE.ROTL_TIP", "Rotate 45° left" },
                { "COPASTE.ROTR_TIP", "Rotate 45° right" },
                { "COPASTE.RAISE_TIP", "Raise 0.5 m (PgUp)" },
                { "COPASTE.LOWER_TIP", "Lower 0.5 m (PgDn)" },
                { "COPASTE.SEC_ALIGN_GAP", "Align props" },
                { "COPASTE.GAP_TIP", "Gap in meters for the align tools (empty = auto). Adjusts a live align too — same as [ and ] keys" },
                { "COPASTE.GAP_AUTO", "auto" },
                { "COPASTE.LINE", "Line" },
                { "COPASTE.LINE_TIP", "Tidy row: straight line, equal gaps AND all props rotated the same way. While lit, [ ] or the stepper adjust the gap" },
                { "COPASTE.TOPROP", "To prop" },
                { "COPASTE.TOPROP_TIP", "Pick a reference prop: the row goes through it, side by side along its facing, all rotated like it. RMB cancels" },
                { "COPASTE.CIRCLE", "Circle" },
                { "COPASTE.CIRCLE_TIP", "Arrange evenly on a circle (stepper = gap in meters, empty = keep size). While lit, [ ] fine-tune" },
                { "COPASTE.SEC_BLUEPRINTS", "Blueprints" },
                { "COPASTE.NO_BLUEPRINTS", "No saved blueprints" },
                { "COPASTE.BP_LOAD_TIP", "Load and start pasting" },
                { "COPASTE.BP_RENAME_TIP", "Rename" },
                { "COPASTE.BP_DELETE_TIP", "Delete blueprint" },
                { "COPASTE.HINT_RELOCATE", "Building follows the cursor • Road snap sets the facing • Click: place • Tab/RMB: cancel" },
                { "COPASTE.HINT_PASTE", "Click: place • RMB drag: rotate • PgUp/PgDn: height • RMB: back" },
                { "COPASTE.HINT_HEIGHT_PICK", "Click a prop to copy its height • RMB: cancel" },
                { "COPASTE.HINT_ALIGN_PICK", "Click a reference prop: row through it, all rotated like it • RMB: cancel" },
                { "COPASTE.HINT_SELECT", "Click/box: select • Ctrl+click: pick overlapped • Alt+drag: move one • Alt+wheel: spin each • RMB drag: rotate" },
            };
        }

        internal static Dictionary<string, string> BuildGerman(CopasteSettings settings)
        {
            return new Dictionary<string, string>
            {
                { settings.GetSettingsLocaleID(), "Copaste" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ToggleBinding)), "Copaste-Werkzeug ein/aus" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ToggleBinding)), "Aktiviert/deaktiviert das Copaste-Auswahlwerkzeug." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.CopyBinding)), "Auswahl kopieren" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.CopyBinding)), "Kopiert die ausgewählten Objekte in die Zwischenablage (solange das Werkzeug aktiv ist)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PasteBinding)), "Einfügen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PasteBinding)), "Startet den Einfügemodus mit einer Vorschau, die der Maus folgt (solange das Werkzeug aktiv ist)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.DeleteBinding)), "Auswahl löschen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.DeleteBinding)), "Löscht die ausgewählten Objekte (solange das Werkzeug aktiv ist)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RaiseBinding)), "Auswahl anheben" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RaiseBinding)), "Hebt die ausgewählten Objekte (oder die Einfüge-Vorschau) an, solange die Taste gedrückt ist." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.LowerBinding)), "Auswahl absenken" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.LowerBinding)), "Senkt die ausgewählten Objekte (oder die Einfüge-Vorschau) ab, solange die Taste gedrückt ist." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.UndoBinding)), "Rückgängig" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.UndoBinding)), "Macht die letzte Copaste-Aktion rückgängig (Verschieben, Drehen, Ausrichten, Höhe, Stupsen, Löschen, Einfügen, Versetzen)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RedoBinding)), "Wiederholen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RedoBinding)), "Wiederholt die zuletzt rückgängig gemachte Copaste-Aktion (Verschieben, Drehen, Ausrichten, Höhe, Stupsen, Löschen, Einfügen, Versetzen)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RelocateBinding)), "Gebäude versetzen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RelocateBinding)), "Startet das Versetzen des ausgewählten Gebäudes (genau ein fertiges Gebäude ausgewählt). Erneut drücken oder Rechtsklick bricht ab." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Gleiche auswählen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Schaltet einen Typfilter um (vom Objekt unter dem Mauszeiger bzw. dem ausgewählten): solange aktiv, erfasst die Rahmenauswahl nur diesen Typ. Erneut drücken zum Aufheben." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Auf Gelände absetzen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Setzt die Auswahl zurück auf das Gelände (setzt die Höhe zurück)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Höhe übernehmen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Aktiviert die Höhenwahl: das nächste angeklickte Objekt bestimmt die Höhe der gesamten Auswahl." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kMatchHeightAction), "Höhe übernehmen" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Schieben: von der Kamera weg" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Verschiebt die Auswahl in kleinen Schritten von der Kamera weg." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Schieben: zur Kamera hin" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Verschiebt die Auswahl in kleinen Schritten zur Kamera hin." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Schieben: nach links" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Verschiebt die Auswahl in kleinen Schritten nach links." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Schieben: nach rechts" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Verschiebt die Auswahl in kleinen Schritten nach rechts." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Ausricht-Abstand +" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Vergrößert den Abstand der letzten Ausrichtung (Line, To prop oder Circle) um 0,5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Ausricht-Abstand -" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Verkleinert den Abstand der letzten Ausrichtung (Line, To prop oder Circle) um 0,5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ModLanguage)), "Mod-Sprache" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ModLanguage)), "Sprache nur für das Copaste-Panel und diese Optionen — das Spiel behält seine eigene Sprache." },
                { settings.GetEnumValueLocaleID(ModLanguageOption.Auto), "Auto (Spielsprache)" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.English), "English" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.German), "Deutsch" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.French), "Français" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.Serbian), "Srpski" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Platzierungsfehler beim Einfügen ignorieren" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Der Einfüge-Stempel ignoriert Platzierungsfehler (Überlappungen, Kollisionen) und wird überall gesetzt. Gilt nur beim Einfügen. Mit installiertem Anarchy-Mod erhalten eingefügte Props und Zäune auch dessen Override-Schutz; Gebäude nicht, ebenso wenig Relocate." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PanelTheme)), "Panel-Design" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PanelTheme)), "Aussehen des Copaste-Panels: eigener Stil des Mods oder Farben und Panels des Spiels (Vanilla)." },
                { settings.GetEnumValueLocaleID(PanelThemeOption.Copaste), "Copaste" },
                { settings.GetEnumValueLocaleID(PanelThemeOption.Vanilla), "Vanilla (Spielstil)" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PanelScale)), "Panelgröße (%)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PanelScale)), "Skaliert das gesamte Copaste-Panel samt Text — falls die Standardgröße zu klein ist." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.TextScale)), "Textgröße (%)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.TextScale)), "Vergrößert nur den Text im Copaste-Panel — das Panel selbst behält seine Größe." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MaxSelection)), "Auswahllimit" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MaxSelection)), "Maximale Anzahl der Objekte in einer Auswahl. Höhere Werte können das Spiel bei großen Aktionen belasten — nur erhöhen, wenn der Rechner mithält." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MaxOverlayShapes)), "Limit für Auswahlmarkierungen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MaxOverlayShapes)), "Maximale Anzahl gleichzeitig gezeichneter Markierungen (Kreise und Zaunlinien). Rein visuell — Objekte über dem Limit bleiben ausgewählt." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectionListMax)), "Limit der Objektliste" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectionListMax)), "Größte Auswahl, für die das Panel noch die Einzelliste zeigt. Lange Listen kosten etwas Leistung, solange das Panel offen ist." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kToggleAction), "Copaste-Werkzeug ein/aus" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kCopyAction), "Auswahl kopieren" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kPasteAction), "Einfügen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kDeleteAction), "Auswahl löschen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRaiseAction), "Auswahl anheben" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kLowerAction), "Auswahl absenken" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kUndoAction), "Rückgängig" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRedoAction), "Wiederholen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRelocateAction), "Gebäude versetzen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSelectSameAction), "Gleiche auswählen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSnapGroundAction), "Auf Gelände absetzen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeUpAction), "Schieben: von der Kamera weg" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeDownAction), "Schieben: zur Kamera hin" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeLeftAction), "Schieben: nach links" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeRightAction), "Schieben: nach rechts" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapPlusAction), "Ausricht-Abstand +" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapMinusAction), "Ausricht-Abstand -" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kGeneralTab), "Allgemein" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kKeybindingsTab), "Tastenbelegung" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kBehaviorGroup), "Verhalten" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kPanelGroup), "Panel" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kLimitsGroup), "Limits" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kToolGroup), "Werkzeug" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kClipboardGroup), "Zwischenablage" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kEditingGroup), "Bearbeiten" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kNudgeGroup), "Feinverschiebung" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kAlignGroup), "Ausrichten" },
                { settings.GetBindingMapLocaleID(), "Copaste" },

                // Panel (cohtml).
                { "COPASTE.STAT_SELECTED", "Ausgewählt" },
                { "COPASTE.STAT_CLIPBOARD", "Ablage" },
                { "COPASTE.CLEAR", "Leeren" },
                { "COPASTE.CLEAR_TIP", "Zwischenablage leeren" },
                { "COPASTE.PROP_LABEL", "Objekt" },
                { "COPASTE.FILTER", "Filter" },
                { "COPASTE.FILTER_OFF", "Aus" },
                { "COPASTE.FILTER_TIP", "Typfilter für die Boxauswahl: sie greift nur diesen Objekttyp. Objekt anklicken zum Setzen, erneut klicken zum Ausschalten (T)" },
                { "COPASTE.SEC_SELECTION", "Auswahl" },
                { "COPASTE.CHIP_SOLO_TIP", "Rechtsklick: nur diese / alle" },
                { "COPASTE.CHIP_PROPS", "Props" },
                { "COPASTE.CHIP_PROPS_TIP", "Bänke, Lampen und andere Props" },
                { "COPASTE.CHIP_TREES", "Bäume" },
                { "COPASTE.CHIP_TREES_TIP", "Bäume, Büsche und andere Vegetation" },
                { "COPASTE.CHIP_DECALS", "Decals" },
                { "COPASTE.CHIP_DECALS_TIP", "Fahrbahnmarkierungen, Flecken und andere Decals" },
                { "COPASTE.CHIP_SURFACES", "Flächen" },
                { "COPASTE.CHIP_SURFACES_TIP", "Gemalte Flächen" },
                { "COPASTE.CHIP_BUILDINGS", "Gebäude" },
                { "COPASTE.CHIP_BUILDINGS_TIP", "Dienstgebäude, Unikate und gewachsene Häuser" },
                { "COPASTE.CHIP_FENCES", "Zäune" },
                { "COPASTE.CHIP_FENCES_TIP", "Entlang einer Linie gezogene Zäune und Hecken" },
                { "COPASTE.CHIP_NETWORKS", "Netze" },
                { "COPASTE.CHIP_NETWORKS_TIP", "Knoten und Segmente von Straßen, Wegen und Gleisen — bewegen, drehen, kopieren und löschen; Strom und Rohre bleiben unberührt" },
                { "COPASTE.SEC_BUILDING_ELEMENTS", "Gebäudeelemente" },
                { "COPASTE.BUILDING_ELEMENTS_TIP", "Wenn aktiv, erfasst die Auswahl auch Elemente, die zu Gebäuden gehören — ihre Props, Bäume, Decals und Grundstücksflächen, jeweils gemäß dem Filter oben. Das Löschen einer Deko-Fläche entfernt auch, was sie immer wieder erzeugt. Wenn aus, ist nichts Gebäudeeigenes auswählbar, auch nicht per Klick" },
                { "COPASTE.ON", "An" },
                { "COPASTE.OFF", "Aus" },
                { "COPASTE.SEC_SELECTED_PROPS", "Ausgewählte Objekte" },
                { "COPASTE.SEC_CLIPBOARD", "Zwischenablage" },
                { "COPASTE.COPY", "Kopieren" },
                { "COPASTE.COPY_TIP", "Auswahl kopieren (Strg+C)" },
                { "COPASTE.PASTE", "Einfügen" },
                { "COPASTE.PASTE_TIP", "Einfügemodus an/aus (Strg+V)" },
                { "COPASTE.SAVE", "Speichern" },
                { "COPASTE.SAVE_TIP", "Auswahl als Blaupause speichern" },
                { "COPASTE.SEC_PASTE_LOOK", "Einfüge-Look" },
                { "COPASTE.PASTE_LOOK_TIP", "Original: eingefügte Objekte behalten die Farbvariante der Vorlage. Zufall: das Spiel wählt eine" },
                { "COPASTE.ORIGINAL", "Original" },
                { "COPASTE.RANDOM", "Zufall" },
                { "COPASTE.UNDERGROUND_TIP", "Untergrund-Ansicht: Klick und Rahmen wählen nur, was unter der Erde liegt (U-Bahn, Tunnel). Kopieren/Einfügen und Undo funktionieren in beiden Welten gleich (U)" },
                { "COPASTE.SEC_ROAD_SNAP", "Straßen-Snap" },
                { "COPASTE.ROAD_SNAP_TIP", "Eingefügte Gebäude rasten wie beim normalen Platzieren an der nächsten Straße ein — die ganze Gruppe dreht sich zu ihr. Solange eingerastet, folgt die Drehung der Straße" },
                { "COPASTE.SEC_EDIT", "Bearbeiten" },
                { "COPASTE.UNDO", "Rückgängig" },
                { "COPASTE.UNDO_TIP", "Letzte Aktion rückgängig machen (Strg+Z)" },
                { "COPASTE.REDO", "Wiederholen" },
                { "COPASTE.REDO_TIP", "Zuletzt Rückgängiges wiederherstellen (Strg+Y)" },
                { "COPASTE.RELOCATE", "Versetzen" },
                { "COPASTE.RELOCATE_TIP", "Ausgewähltes Gebäude versetzen (Tab): es folgt dem Cursor, der Straßen-Snap bestimmt die Ausrichtung. Klick platziert, Tab oder Rechtsklick bricht ab. Zum freien Drehen erst platzieren, dann RMT ziehen" },
                { "COPASTE.DELETE", "Löschen" },
                { "COPASTE.DELETE_TIP", "Auswahl löschen (Entf)" },
                { "COPASTE.SEC_ALIGN", "Ausrichten" },
                { "COPASTE.GROUND", "Boden" },
                { "COPASTE.GROUND_TIP", "Auswahl aufs Gelände setzen (Ende)" },
                { "COPASTE.MATCHH", "Höhe wie" },
                { "COPASTE.MATCHH_TIP", "Höhe von einem Objekt übernehmen (Pos1)" },
                { "COPASTE.ROTL_TIP", "45° nach links drehen" },
                { "COPASTE.ROTR_TIP", "45° nach rechts drehen" },
                { "COPASTE.RAISE_TIP", "0,5 m anheben (Bild↑)" },
                { "COPASTE.LOWER_TIP", "0,5 m absenken (Bild↓)" },
                { "COPASTE.SEC_ALIGN_GAP", "Objekte ausrichten" },
                { "COPASTE.GAP_TIP", "Abstand in Metern für die Ausricht-Werkzeuge (leer = auto). Wirkt auch auf eine laufende Ausrichtung — wie die Tasten [ und ]" },
                { "COPASTE.GAP_AUTO", "auto" },
                { "COPASTE.LINE", "Linie" },
                { "COPASTE.LINE_TIP", "Ordentliche Reihe: gerade Linie, gleiche Abstände UND alle Objekte gleich gedreht. Solange aktiv, ändern [ ] oder der Regler den Abstand" },
                { "COPASTE.TOPROP", "An Objekt" },
                { "COPASTE.TOPROP_TIP", "Referenzobjekt wählen: die Reihe verläuft durch dieses Objekt, entlang seiner Ausrichtung, alle gleich gedreht. RMT bricht ab" },
                { "COPASTE.CIRCLE", "Kreis" },
                { "COPASTE.CIRCLE_TIP", "Gleichmäßig auf einem Kreis anordnen (Regler = Abstand in Metern, leer = Größe behalten). Solange aktiv, feinjustieren [ ]" },
                { "COPASTE.SEC_BLUEPRINTS", "Blaupausen" },
                { "COPASTE.NO_BLUEPRINTS", "Keine gespeicherten Blaupausen" },
                { "COPASTE.BP_LOAD_TIP", "Laden und einfügen" },
                { "COPASTE.BP_RENAME_TIP", "Umbenennen" },
                { "COPASTE.BP_DELETE_TIP", "Blaupause löschen" },
                { "COPASTE.HINT_RELOCATE", "Gebäude folgt dem Cursor • Straßen-Snap bestimmt die Ausrichtung • Klick: platzieren • Tab/RMT: abbrechen" },
                { "COPASTE.HINT_PASTE", "Klick: platzieren • RMT ziehen: drehen • Bild↑/Bild↓: Höhe • RMT: zurück" },
                { "COPASTE.HINT_HEIGHT_PICK", "Objekt anklicken, um seine Höhe zu übernehmen • RMT: abbrechen" },
                { "COPASTE.HINT_ALIGN_PICK", "Referenzobjekt anklicken: Reihe durch das Objekt, alle gleich gedreht • RMT: abbrechen" },
                { "COPASTE.HINT_SELECT", "Klick/Box: auswählen • Strg+Klick: Verdecktes greifen • Alt+Ziehen: eines bewegen • Alt+Rad: einzeln drehen • RMT ziehen: rotieren" },
            };
        }

        internal static Dictionary<string, string> BuildFrench(CopasteSettings settings)
        {
            return new Dictionary<string, string>
            {
                { settings.GetSettingsLocaleID(), "Copaste" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ToggleBinding)), "Activer/désactiver l'outil Copaste" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ToggleBinding)), "Active ou désactive l'outil de sélection Copaste." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.CopyBinding)), "Copier la sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.CopyBinding)), "Copie les objets sélectionnés dans le presse-papiers (quand l'outil est actif)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PasteBinding)), "Coller" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PasteBinding)), "Passe en mode collage avec un aperçu qui suit la souris (quand l'outil est actif)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.DeleteBinding)), "Supprimer la sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.DeleteBinding)), "Supprime les objets sélectionnés (quand l'outil est actif)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RaiseBinding)), "Élever la sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RaiseBinding)), "Élève les objets sélectionnés (ou l'aperçu de collage) tant que la touche est maintenue." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.LowerBinding)), "Abaisser la sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.LowerBinding)), "Abaisse les objets sélectionnés (ou l'aperçu de collage) tant que la touche est maintenue." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.UndoBinding)), "Annuler" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.UndoBinding)), "Annule la dernière action Copaste (déplacement, rotation, alignement, hauteur, décalage, suppression, collage, relocalisation)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RedoBinding)), "Rétablir" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RedoBinding)), "Rétablit la dernière action Copaste annulée (déplacement, rotation, alignement, hauteur, décalage, suppression, collage, relocalisation)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RelocateBinding)), "Déplacer le bâtiment" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RelocateBinding)), "Lance le déplacement du bâtiment sélectionné (exactement un bâtiment terminé sélectionné). Appuyez à nouveau ou clic droit pour annuler." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Sélectionner identiques" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Active un filtre de type (pris sur l'objet survolé/sélectionné) : tant qu'il est actif, la sélection au cadre ne prend que ce type. Appuyez à nouveau pour l'effacer." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Poser au sol" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Repose la sélection sur le terrain (réinitialise la hauteur)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Reprendre la hauteur" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Arme le choix de hauteur : le prochain objet cliqué définit la hauteur de toute la sélection." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kMatchHeightAction), "Reprendre la hauteur" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Décaler : loin de la caméra" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Décale légèrement la sélection en s'éloignant de la caméra." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Décaler : vers la caméra" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Décale légèrement la sélection vers la caméra." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Décaler : à gauche" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Décale légèrement la sélection vers la gauche." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Décaler : à droite" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Décale légèrement la sélection vers la droite." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Espacement d'alignement +" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Augmente de 0,5 m l'espacement du dernier alignement (Line, To prop ou Circle)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Espacement d'alignement -" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Réduit de 0,5 m l'espacement du dernier alignement (Line, To prop ou Circle)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ModLanguage)), "Langue du mod" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ModLanguage)), "Langue du panneau Copaste et de ces options uniquement — le jeu garde sa propre langue." },
                { settings.GetEnumValueLocaleID(ModLanguageOption.Auto), "Auto (langue du jeu)" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.English), "English" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.German), "Deutsch" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.French), "Français" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.Serbian), "Srpski" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Ignorer les erreurs de placement au collage" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Le collage ignore les erreurs de placement (chevauchements, collisions) et se pose n'importe où. Au collage uniquement. Avec le mod Anarchy installé, les props et clôtures collés reçoivent aussi sa protection anti-override ; pas les bâtiments, ni Relocate." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PanelTheme)), "Thème du panneau" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PanelTheme)), "Apparence du panneau Copaste : le style du mod, ou les couleurs et panneaux du jeu (vanilla)." },
                { settings.GetEnumValueLocaleID(PanelThemeOption.Copaste), "Copaste" },
                { settings.GetEnumValueLocaleID(PanelThemeOption.Vanilla), "Vanilla (style du jeu)" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PanelScale)), "Taille du panneau (%)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PanelScale)), "Agrandit tout le panneau Copaste, texte compris — pour ceux qui trouvent la taille par défaut trop petite." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.TextScale)), "Taille du texte (%)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.TextScale)), "N'agrandit que le texte du panneau Copaste — le panneau garde sa taille." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MaxSelection)), "Limite de sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MaxSelection)), "Nombre maximal d'objets dans une sélection. Des valeurs élevées peuvent solliciter le jeu lors de grandes opérations — à augmenter seulement si votre machine suit." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MaxOverlayShapes)), "Limite des contours de sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MaxOverlayShapes)), "Nombre maximal de contours (cercles et lignes de clôture) affichés à la fois. Purement visuel — les objets au-delà de la limite restent sélectionnés." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectionListMax)), "Limite de la liste d'objets" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectionListMax)), "Taille maximale de sélection pour laquelle le panneau affiche encore la liste détaillée. Les longues listes coûtent un peu de performance tant que le panneau est ouvert." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kToggleAction), "Activer/désactiver l'outil Copaste" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kCopyAction), "Copier la sélection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kPasteAction), "Coller" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kDeleteAction), "Supprimer la sélection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRaiseAction), "Élever la sélection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kLowerAction), "Abaisser la sélection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kUndoAction), "Annuler" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRedoAction), "Rétablir" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRelocateAction), "Déplacer le bâtiment" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSelectSameAction), "Sélectionner identiques" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSnapGroundAction), "Poser au sol" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeUpAction), "Décaler : loin de la caméra" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeDownAction), "Décaler : vers la caméra" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeLeftAction), "Décaler : à gauche" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeRightAction), "Décaler : à droite" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapPlusAction), "Espacement d'alignement +" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapMinusAction), "Espacement d'alignement -" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kGeneralTab), "Général" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kKeybindingsTab), "Raccourcis clavier" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kBehaviorGroup), "Comportement" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kPanelGroup), "Panneau" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kLimitsGroup), "Limites" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kToolGroup), "Outil" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kClipboardGroup), "Presse-papiers" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kEditingGroup), "Édition" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kNudgeGroup), "Décalage fin" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kAlignGroup), "Alignement" },
                { settings.GetBindingMapLocaleID(), "Copaste" },

                // Panel (cohtml).
                { "COPASTE.STAT_SELECTED", "Sélection" },
                { "COPASTE.STAT_CLIPBOARD", "Presse-papiers" },
                { "COPASTE.CLEAR", "Vider" },
                { "COPASTE.CLEAR_TIP", "Vider le presse-papiers" },
                { "COPASTE.PROP_LABEL", "Objet" },
                { "COPASTE.FILTER", "Filtre" },
                { "COPASTE.FILTER_OFF", "Off" },
                { "COPASTE.FILTER_TIP", "Filtre de type pour la sélection rectangulaire : elle ne prend que ce type d'objet. Cliquer un objet pour le définir, recliquer pour désactiver (T)" },
                { "COPASTE.SEC_SELECTION", "Sélection" },
                { "COPASTE.CHIP_SOLO_TIP", "Clic droit : celui-ci seul / tout" },
                { "COPASTE.CHIP_PROPS", "Props" },
                { "COPASTE.CHIP_PROPS_TIP", "Bancs, lampadaires et autres props" },
                { "COPASTE.CHIP_TREES", "Arbres" },
                { "COPASTE.CHIP_TREES_TIP", "Arbres, buissons et autre végétation" },
                { "COPASTE.CHIP_DECALS", "Décals" },
                { "COPASTE.CHIP_DECALS_TIP", "Marquages routiers, taches et autres décals" },
                { "COPASTE.CHIP_SURFACES", "Surfaces" },
                { "COPASTE.CHIP_SURFACES_TIP", "Surfaces peintes" },
                { "COPASTE.CHIP_BUILDINGS", "Bâtiments" },
                { "COPASTE.CHIP_BUILDINGS_TIP", "Bâtiments de service, uniques et maisons de zonage" },
                { "COPASTE.CHIP_FENCES", "Clôtures" },
                { "COPASTE.CHIP_FENCES_TIP", "Clôtures et haies tracées le long d'une ligne" },
                { "COPASTE.CHIP_NETWORKS", "Réseaux" },
                { "COPASTE.CHIP_NETWORKS_TIP", "Nœuds et segments de routes, chemins et voies — déplacer, pivoter, copier et supprimer ; lignes et tuyaux non touchés" },
                { "COPASTE.SEC_BUILDING_ELEMENTS", "Éléments de bâtiment" },
                { "COPASTE.BUILDING_ELEMENTS_TIP", "Si activé, la sélection atteint aussi les éléments appartenant aux bâtiments — leurs props, arbres, décals et surfaces de parcelle, chacun selon son filtre ci-dessus. Supprimer une surface décorative retire aussi ce qu'elle fait réapparaître. Si désactivé, rien d'appartenant à un bâtiment n'est sélectionnable, même au clic" },
                { "COPASTE.ON", "On" },
                { "COPASTE.OFF", "Off" },
                { "COPASTE.SEC_SELECTED_PROPS", "Objets sélectionnés" },
                { "COPASTE.SEC_CLIPBOARD", "Presse-papiers" },
                { "COPASTE.COPY", "Copier" },
                { "COPASTE.COPY_TIP", "Copier la sélection (Ctrl+C)" },
                { "COPASTE.PASTE", "Coller" },
                { "COPASTE.PASTE_TIP", "Mode collage on/off (Ctrl+V)" },
                { "COPASTE.SAVE", "Sauver" },
                { "COPASTE.SAVE_TIP", "Enregistrer la sélection comme plan" },
                { "COPASTE.SEC_PASTE_LOOK", "Style de collage" },
                { "COPASTE.PASTE_LOOK_TIP", "Original : les objets collés gardent la variante de couleur de l'original. Aléatoire : le jeu en choisit une" },
                { "COPASTE.ORIGINAL", "Original" },
                { "COPASTE.RANDOM", "Aléatoire" },
                { "COPASTE.UNDERGROUND_TIP", "Vue souterraine : le clic et le cadre ne sélectionnent que ce qui est sous terre (métro, tunnels). Copier/coller et annuler fonctionnent pareil dans les deux mondes (U)" },
                { "COPASTE.SEC_ROAD_SNAP", "Accroche route" },
                { "COPASTE.ROAD_SNAP_TIP", "Les bâtiments collés s'accrochent à la route la plus proche comme au placement normal — tout le groupe pivote pour lui faire face. Tant que c'est accroché, la rotation suit la route" },
                { "COPASTE.SEC_EDIT", "Édition" },
                { "COPASTE.UNDO", "Annuler" },
                { "COPASTE.UNDO_TIP", "Annuler la dernière action (Ctrl+Z)" },
                { "COPASTE.REDO", "Rétablir" },
                { "COPASTE.REDO_TIP", "Rétablir la dernière action annulée (Ctrl+Y)" },
                { "COPASTE.RELOCATE", "Déplacer" },
                { "COPASTE.RELOCATE_TIP", "Déplacer le bâtiment sélectionné (Tab) : il suit le curseur, l'accroche route fixe l'orientation. Clic pour poser, Tab ou clic droit pour annuler. Pour pivoter librement, posez-le d'abord puis glissez avec le clic droit" },
                { "COPASTE.DELETE", "Supprimer" },
                { "COPASTE.DELETE_TIP", "Supprimer la sélection (Suppr)" },
                { "COPASTE.SEC_ALIGN", "Alignement" },
                { "COPASTE.GROUND", "Sol" },
                { "COPASTE.GROUND_TIP", "Poser la sélection sur le terrain (Fin)" },
                { "COPASTE.MATCHH", "Même haut." },
                { "COPASTE.MATCHH_TIP", "Prendre la hauteur d'un objet (Début)" },
                { "COPASTE.ROTL_TIP", "Pivoter de 45° à gauche" },
                { "COPASTE.ROTR_TIP", "Pivoter de 45° à droite" },
                { "COPASTE.RAISE_TIP", "Monter de 0,5 m (Pg↑)" },
                { "COPASTE.LOWER_TIP", "Descendre de 0,5 m (Pg↓)" },
                { "COPASTE.SEC_ALIGN_GAP", "Aligner les objets" },
                { "COPASTE.GAP_TIP", "Espacement en mètres pour les outils d'alignement (vide = auto). Agit aussi sur un alignement en cours — comme les touches [ et ]" },
                { "COPASTE.GAP_AUTO", "auto" },
                { "COPASTE.LINE", "Ligne" },
                { "COPASTE.LINE_TIP", "Rangée nette : ligne droite, espacements égaux ET tous les objets orientés pareil. Tant que c'est actif, [ ] ou le curseur ajustent l'espacement" },
                { "COPASTE.TOPROP", "Sur objet" },
                { "COPASTE.TOPROP_TIP", "Choisir un objet de référence : la rangée passe par lui, côte à côte selon son orientation, tous orientés comme lui. Clic droit annule" },
                { "COPASTE.CIRCLE", "Cercle" },
                { "COPASTE.CIRCLE_TIP", "Répartir uniformément sur un cercle (curseur = espacement en mètres, vide = garder la taille). Tant que c'est actif, [ ] affinent" },
                { "COPASTE.SEC_BLUEPRINTS", "Plans" },
                { "COPASTE.NO_BLUEPRINTS", "Aucun plan enregistré" },
                { "COPASTE.BP_LOAD_TIP", "Charger et coller" },
                { "COPASTE.BP_RENAME_TIP", "Renommer" },
                { "COPASTE.BP_DELETE_TIP", "Supprimer le plan" },
                { "COPASTE.HINT_RELOCATE", "Le bâtiment suit le curseur • L'accroche route fixe l'orientation • Clic : poser • Tab/clic droit : annuler" },
                { "COPASTE.HINT_PASTE", "Clic : poser • Glisser clic droit : pivoter • Pg↑/Pg↓ : hauteur • Clic droit : retour" },
                { "COPASTE.HINT_HEIGHT_PICK", "Cliquer un objet pour copier sa hauteur • Clic droit : annuler" },
                { "COPASTE.HINT_ALIGN_PICK", "Cliquer un objet de référence : rangée passant par lui, tous orientés pareil • Clic droit : annuler" },
                { "COPASTE.HINT_SELECT", "Clic/boîte : sélectionner • Ctrl+clic : prendre le recouvert • Alt+glisser : bouger un seul • Alt+molette : pivoter chacun • Glisser clic droit : rotation" },
            };
        }

        internal static Dictionary<string, string> BuildSerbian(CopasteSettings settings)
        {
            return new Dictionary<string, string>
            {
                { settings.GetSettingsLocaleID(), "Copaste" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ToggleBinding)), "Uključi/isključi Copaste alat" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ToggleBinding)), "Aktivira/deaktivira Copaste alat za selekciju." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.CopyBinding)), "Kopiraj selekciju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.CopyBinding)), "Kopira selektovane propove u clipboard (dok je alat aktivan)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PasteBinding)), "Nalepi" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PasteBinding)), "Ulazi u paste mod sa preview-om koji prati miš (dok je alat aktivan)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.DeleteBinding)), "Obriši selekciju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.DeleteBinding)), "Briše selektovane propove (dok je alat aktivan)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RaiseBinding)), "Podigni selekciju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RaiseBinding)), "Podiže selektovane propove (ili paste preview) dok je taster pritisnut." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.LowerBinding)), "Spusti selekciju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.LowerBinding)), "Spušta selektovane propove (ili paste preview) dok je taster pritisnut." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.UndoBinding)), "Poništi (Undo)" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RedoBinding)), "Ponovi (Redo)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RedoBinding)), "Ponavlja poslednju poništenu Copaste akciju (pomeranje, rotacija, poravnanje, visina, pomak, brisanje, lepljenje, premeštanje)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RelocateBinding)), "Premesti zgradu (Relocate)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RelocateBinding)), "Pokreće premeštanje selektovane zgrade (tačno jedna završena zgrada u selekciji). Ponovni pritisak ili desni klik odustaje." },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.UndoBinding)), "Poništava poslednju Copaste akciju (pomeranje, rotaciju, poravnanje, visinu, pomak, brisanje, lepljenje, premeštanje)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Selektuj iste" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Uključuje filter tipa (uzet od propa pod mišem/selektovanog): dok je aktivan, marquee hvata samo taj tip. Ponovni pritisak gasi filter." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Spusti na teren" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Vraća selekciju na visinu terena (resetuje visinu)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Preuzmi visinu" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Aktivira biranje visine: sledeći prop na koji klikneš zadaje visinu celoj selekciji." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kMatchHeightAction), "Preuzmi visinu" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Pomak od kamere" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Fino pomera selekciju od kamere." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Pomak ka kameri" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Fino pomera selekciju ka kameri." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Pomak levo" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Fino pomera selekciju ulevo." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Pomak desno" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Fino pomera selekciju udesno." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Align razmak +" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Povećava razmak poslednjeg poravnanja (Line, To prop ili Circle) za 0,5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Align razmak -" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Smanjuje razmak poslednjeg poravnanja (Line, To prop ili Circle) za 0,5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ModLanguage)), "Jezik moda" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ModLanguage)), "Jezik samo za Copaste panel i ova podešavanja — igra zadržava svoj jezik." },
                { settings.GetEnumValueLocaleID(ModLanguageOption.Auto), "Auto (jezik igre)" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.English), "English" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.German), "Deutsch" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.French), "Français" },
                { settings.GetEnumValueLocaleID(ModLanguageOption.Serbian), "Srpski" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Ignoriši greške postavljanja pri lepljenju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Stamp pri lepljenju ignoriše greške postavljanja (preklapanja, kolizije), pa legne bilo gde. Važi samo za lepljenje. Uz instaliran Anarchy mod, nalepljeni propovi i ograde dobijaju i njegovu zaštitu od override-a; zgrade ne, kao ni Relocate — zgrada pomerena u drugu i dalje može da izazove uklanjanje jedne." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PanelTheme)), "Izgled panela" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PanelTheme)), "Kako Copaste panel izgleda: stil moda, ili boje i paneli iz igre (vanila)." },
                { settings.GetEnumValueLocaleID(PanelThemeOption.Copaste), "Copaste" },
                { settings.GetEnumValueLocaleID(PanelThemeOption.Vanilla), "Vanila (stil igre)" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PanelScale)), "Veličina panela (%)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PanelScale)), "Uvećava ceo Copaste panel, uključujući tekst — ako je nekome podrazumevano sitno." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.TextScale)), "Veličina teksta (%)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.TextScale)), "Uvećava samo tekst na Copaste panelu — panel zadržava svoju veličinu." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MaxSelection)), "Limit selekcije" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MaxSelection)), "Najveći broj objekata u jednoj selekciji. Veće vrednosti mogu da opterete igru pri velikim operacijama — povećavaj samo ako mašina prati." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MaxOverlayShapes)), "Limit oznaka selekcije" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MaxOverlayShapes)), "Najveći broj istovremeno iscrtanih oznaka (krugova i linija ograda). Čisto vizuelno — objekti preko limita ostaju selektovani." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectionListMax)), "Limit liste propova" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectionListMax)), "Najveća selekcija za koju panel još prikazuje pojedinačnu listu. Duge liste troše malo performansi dok je panel otvoren." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kToggleAction), "Uključi/isključi Copaste alat" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kCopyAction), "Kopiraj selekciju" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kPasteAction), "Nalepi" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kDeleteAction), "Obriši selekciju" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRaiseAction), "Podigni selekciju" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kLowerAction), "Spusti selekciju" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kUndoAction), "Poništi (Undo)" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRedoAction), "Ponovi (Redo)" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRelocateAction), "Premesti zgradu (Relocate)" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSelectSameAction), "Selektuj iste" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSnapGroundAction), "Spusti na teren" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeUpAction), "Pomak od kamere" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeDownAction), "Pomak ka kameri" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeLeftAction), "Pomak levo" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeRightAction), "Pomak desno" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapPlusAction), "Align razmak +" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapMinusAction), "Align razmak -" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kGeneralTab), "Opšte" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kKeybindingsTab), "Prečice" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kBehaviorGroup), "Ponašanje" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kPanelGroup), "Panel" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kLimitsGroup), "Limiti" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kToolGroup), "Alat" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kClipboardGroup), "Clipboard" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kEditingGroup), "Uređivanje" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kNudgeGroup), "Fini pomak" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kAlignGroup), "Poravnanje" },
                { settings.GetBindingMapLocaleID(), "Copaste" },

                // Panel (cohtml).
                { "COPASTE.STAT_SELECTED", "Selektovano" },
                { "COPASTE.STAT_CLIPBOARD", "Clipboard" },
                { "COPASTE.CLEAR", "Isprazni" },
                { "COPASTE.CLEAR_TIP", "Isprazni clipboard" },
                { "COPASTE.PROP_LABEL", "Prop" },
                { "COPASTE.FILTER", "Filter" },
                { "COPASTE.FILTER_OFF", "Isklj." },
                { "COPASTE.FILTER_TIP", "Filter tipa za box selekciju: hvata samo ovaj tip propa. Klikni prop da ga postaviš, klikni opet da isključiš (T)" },
                { "COPASTE.SEC_SELECTION", "Selekcija" },
                { "COPASTE.CHIP_SOLO_TIP", "Desni klik: samo ovaj / sve" },
                { "COPASTE.CHIP_PROPS", "Propovi" },
                { "COPASTE.CHIP_PROPS_TIP", "Klupe, lampe i ostali propovi" },
                { "COPASTE.CHIP_TREES", "Drveće" },
                { "COPASTE.CHIP_TREES_TIP", "Drveće, žbunje i ostala vegetacija" },
                { "COPASTE.CHIP_DECALS", "Dekali" },
                { "COPASTE.CHIP_DECALS_TIP", "Oznake na putu, fleke i ostali dekali" },
                { "COPASTE.CHIP_SURFACES", "Površine" },
                { "COPASTE.CHIP_SURFACES_TIP", "Farbane površine" },
                { "COPASTE.CHIP_BUILDINGS", "Zgrade" },
                { "COPASTE.CHIP_BUILDINGS_TIP", "Servisne zgrade, jedinstvene i izrasle kuće" },
                { "COPASTE.CHIP_FENCES", "Ograde" },
                { "COPASTE.CHIP_FENCES_TIP", "Ograde i živice povučene duž linije" },
                { "COPASTE.CHIP_NETWORKS", "Mreže" },
                { "COPASTE.CHIP_NETWORKS_TIP", "Čvorovi i segmenti puteva, staza i šina — pomeranje, rotacija, kopiranje i brisanje; struja i cevi se ne diraju" },
                { "COPASTE.SEC_BUILDING_ELEMENTS", "Elementi zgrada" },
                { "COPASTE.BUILDING_ELEMENTS_TIP", "Kad je uključeno, selekcija hvata i elemente koji pripadaju zgradama — njihove propove, drveće, dekale i površine placa, svaki po svom filteru iznad. Brisanje dekorativne površine uklanja i ono što ona stalno stvara. Kad je isključeno, ništa zgradino se ne bira, ni klikom" },
                { "COPASTE.ON", "Uklj." },
                { "COPASTE.OFF", "Isklj." },
                { "COPASTE.SEC_SELECTED_PROPS", "Selektovani propovi" },
                { "COPASTE.SEC_CLIPBOARD", "Clipboard" },
                { "COPASTE.COPY", "Kopiraj" },
                { "COPASTE.COPY_TIP", "Kopiraj selekciju (Ctrl+C)" },
                { "COPASTE.PASTE", "Nalepi" },
                { "COPASTE.PASTE_TIP", "Paste mod uklj/isklj (Ctrl+V)" },
                { "COPASTE.SAVE", "Sačuvaj" },
                { "COPASTE.SAVE_TIP", "Sačuvaj selekciju kao blueprint" },
                { "COPASTE.SEC_PASTE_LOOK", "Izgled paste-a" },
                { "COPASTE.PASTE_LOOK_TIP", "Original: nalepljeni propovi zadržavaju varijaciju boje originala. Nasumično: igra bira" },
                { "COPASTE.ORIGINAL", "Original" },
                { "COPASTE.RANDOM", "Nasumično" },
                { "COPASTE.UNDERGROUND_TIP", "Podzemni prikaz: klik i okvir biraju samo ono što je ispod zemlje (metro, tuneli). Copy/paste i undo rade isto u oba sveta (U)" },
                { "COPASTE.SEC_ROAD_SNAP", "Lepljenje uz put" },
                { "COPASTE.ROAD_SNAP_TIP", "Nalepljene zgrade se lepe uz najbliži put kao pri običnom postavljanju — cela grupa se okrene ka njemu. Dok je zalepljeno, rotacija prati put" },
                { "COPASTE.SEC_EDIT", "Uređivanje" },
                { "COPASTE.UNDO", "Vrati" },
                { "COPASTE.UNDO_TIP", "Vrati poslednju akciju (Ctrl+Z)" },
                { "COPASTE.REDO", "Ponovi" },
                { "COPASTE.REDO_TIP", "Ponovi poslednju vraćenu akciju (Ctrl+Y)" },
                { "COPASTE.RELOCATE", "Premesti" },
                { "COPASTE.RELOCATE_TIP", "Premesti selektovanu zgradu (Tab): prati kursor, lepljenje uz put određuje okrenutost. Klik spušta, Tab ili desni klik otkazuje. Za slobodnu rotaciju prvo je spusti pa vuci desnim klikom" },
                { "COPASTE.DELETE", "Obriši" },
                { "COPASTE.DELETE_TIP", "Obriši selekciju (Del)" },
                { "COPASTE.SEC_ALIGN", "Poravnanje" },
                { "COPASTE.GROUND", "Tlo" },
                { "COPASTE.GROUND_TIP", "Spusti selekciju na teren (End)" },
                { "COPASTE.MATCHH", "Ista visina" },
                { "COPASTE.MATCHH_TIP", "Uzmi visinu sa propa (Home)" },
                { "COPASTE.ROTL_TIP", "Rotiraj 45° ulevo" },
                { "COPASTE.ROTR_TIP", "Rotiraj 45° udesno" },
                { "COPASTE.RAISE_TIP", "Podigni 0,5 m (PgUp)" },
                { "COPASTE.LOWER_TIP", "Spusti 0,5 m (PgDn)" },
                { "COPASTE.SEC_ALIGN_GAP", "Poravnaj propove" },
                { "COPASTE.GAP_TIP", "Razmak u metrima za alate poravnanja (prazno = auto). Menja i živo poravnanje — isto kao tasteri [ i ]" },
                { "COPASTE.GAP_AUTO", "auto" },
                { "COPASTE.LINE", "Linija" },
                { "COPASTE.LINE_TIP", "Uredan red: prava linija, jednaki razmaci I svi propovi isto okrenuti. Dok svetli, [ ] ili stepper menjaju razmak" },
                { "COPASTE.TOPROP", "Na prop" },
                { "COPASTE.TOPROP_TIP", "Izaberi referentni prop: red ide kroz njega, rame uz rame duž njegove okrenutosti, svi okrenuti kao on. Desni klik otkazuje" },
                { "COPASTE.CIRCLE", "Krug" },
                { "COPASTE.CIRCLE_TIP", "Rasporedi ravnomerno po krugu (stepper = razmak u metrima, prazno = zadrži veličinu). Dok svetli, [ ] fino doteruju" },
                { "COPASTE.SEC_BLUEPRINTS", "Blueprints" },
                { "COPASTE.NO_BLUEPRINTS", "Nema sačuvanih blueprint-a" },
                { "COPASTE.BP_LOAD_TIP", "Učitaj i kreni sa lepljenjem" },
                { "COPASTE.BP_RENAME_TIP", "Preimenuj" },
                { "COPASTE.BP_DELETE_TIP", "Obriši blueprint" },
                { "COPASTE.HINT_RELOCATE", "Zgrada prati kursor • Lepljenje uz put određuje okrenutost • Klik: spusti • Tab/desni klik: otkaži" },
                { "COPASTE.HINT_PASTE", "Klik: nalepi • Desni klik + vuci: rotiraj • PgUp/PgDn: visina • Desni klik: nazad" },
                { "COPASTE.HINT_HEIGHT_PICK", "Klikni prop da uzmeš njegovu visinu • Desni klik: otkaži" },
                { "COPASTE.HINT_ALIGN_PICK", "Klikni referentni prop: red kroz njega, svi okrenuti kao on • Desni klik: otkaži" },
                { "COPASTE.HINT_SELECT", "Klik/box: selektuj • Ctrl+klik: uhvati preklopljeno • Alt+vuci: pomeri jedan • Alt+točkić: zavrti svaki • Desni klik + vuci: rotiraj" },
            };
        }
    }
}
