namespace Copaste
{
    using System.Collections.Generic;

    internal static class Localization
    {
        internal static Dictionary<string, string> BuildEnglish(CopasteSettings settings)
        {
            return new Dictionary<string, string>
            {
                { settings.GetSettingsLocaleID(), "Copaste" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ToggleBinding)), "Toggle Copaste tool" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ToggleBinding)), "Activates/deactivates the Copaste selection tool." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.CopyBinding)), "Copy selection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.CopyBinding)), "Copies the selected props to the clipboard (while the tool is active)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PasteBinding)), "Paste" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PasteBinding)), "Enters paste mode with a preview following the mouse (while the tool is active)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.DeleteBinding)), "Delete selection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.DeleteBinding)), "Deletes the selected props (while the tool is active)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RaiseBinding)), "Raise selection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RaiseBinding)), "Raises the selected props (or the paste preview) while held." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.LowerBinding)), "Lower selection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.LowerBinding)), "Lowers the selected props (or the paste preview) while held." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.UndoBinding)), "Undo" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RedoBinding)), "Redo" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RedoBinding)), "Redoes the last undone Copaste action (move, rotate, align, height, delete, paste)." },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.UndoBinding)), "Undoes the last Copaste action (move, rotate, height, delete, paste)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RelocateBinding)), "Relocate building" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RelocateBinding)), "Starts Relocate for the selected building (exactly one finished building selected). Press again or right-click to cancel." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Select same" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Toggles a type filter taken from the hovered/selected prop: while active, marquee selection only picks props of that type. Press again to clear." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Snap to ground" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Drops the selection back onto the terrain (resets height)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Match height" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Arms height picking: the next prop you click sets the height for the whole selection." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kMatchHeightAction), "Match height" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Nudge away" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Nudges the selection away from the camera." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Nudge towards" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Nudges the selection towards the camera." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Nudge left" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Nudges the selection to the left." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Nudge right" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Nudges the selection to the right." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Align gap +" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Increases the gap of the last align (Line, To prop or Circle) by 0.5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Align gap -" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Decreases the gap of the last align (Line, To prop or Circle) by 0.5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Anarchy while pasting" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Ignores placement errors (overlaps, collisions) while pasting, so props can be placed anywhere — like the Anarchy mod." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kToggleAction), "Toggle Copaste tool" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kCopyAction), "Copy selection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kPasteAction), "Paste" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kDeleteAction), "Delete selection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRaiseAction), "Raise selection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kLowerAction), "Lower selection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kUndoAction), "Undo" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRedoAction), "Redo" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRelocateAction), "Relocate building" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSelectSameAction), "Select same" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSnapGroundAction), "Snap to ground" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeUpAction), "Nudge away" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeDownAction), "Nudge towards" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeLeftAction), "Nudge left" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeRightAction), "Nudge right" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapPlusAction), "Align gap +" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapMinusAction), "Align gap -" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kGeneralTab), "General" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kKeybindingsTab), "Key bindings" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kBehaviorGroup), "Behavior" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kToolGroup), "Tool" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kClipboardGroup), "Clipboard" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kEditingGroup), "Editing" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kNudgeGroup), "Nudge" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kAlignGroup), "Align" },
                { settings.GetBindingMapLocaleID(), "Copaste" },
            };
        }

        internal static Dictionary<string, string> BuildGerman(CopasteSettings settings)
        {
            return new Dictionary<string, string>
            {
                { settings.GetSettingsLocaleID(), "Copaste" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ToggleBinding)), "Copaste-Werkzeug ein/aus" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ToggleBinding)), "Aktiviert/deaktiviert das Copaste-Auswahlwerkzeug." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.CopyBinding)), "Auswahl kopieren" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.CopyBinding)), "Kopiert die ausgewählten Objekte in die Zwischenablage (solange das Werkzeug aktiv ist)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PasteBinding)), "Einfügen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PasteBinding)), "Startet den Einfügemodus mit einer Vorschau, die der Maus folgt (solange das Werkzeug aktiv ist)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.DeleteBinding)), "Auswahl löschen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.DeleteBinding)), "Löscht die ausgewählten Objekte (solange das Werkzeug aktiv ist)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RaiseBinding)), "Auswahl anheben" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RaiseBinding)), "Hebt die ausgewählten Objekte (oder die Einfüge-Vorschau) an, solange die Taste gedrückt ist." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.LowerBinding)), "Auswahl absenken" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.LowerBinding)), "Senkt die ausgewählten Objekte (oder die Einfüge-Vorschau) ab, solange die Taste gedrückt ist." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.UndoBinding)), "Rückgängig" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.UndoBinding)), "Macht die letzte Copaste-Aktion rückgängig (Verschieben, Drehen, Höhe, Löschen, Einfügen)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RedoBinding)), "Wiederholen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RedoBinding)), "Wiederholt die zuletzt rückgängig gemachte Copaste-Aktion (Verschieben, Drehen, Ausrichten, Höhe, Löschen, Einfügen)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RelocateBinding)), "Gebäude versetzen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RelocateBinding)), "Startet das Versetzen des ausgewählten Gebäudes (genau ein fertiges Gebäude ausgewählt). Erneut drücken oder Rechtsklick bricht ab." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Gleiche auswählen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Schaltet einen Typfilter um (vom Objekt unter dem Mauszeiger bzw. dem ausgewählten): solange aktiv, erfasst die Rahmenauswahl nur diesen Typ. Erneut drücken zum Aufheben." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Auf Gelände absetzen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Setzt die Auswahl zurück auf das Gelände (setzt die Höhe zurück)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Höhe übernehmen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Aktiviert die Höhenwahl: das nächste angeklickte Objekt bestimmt die Höhe der gesamten Auswahl." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kMatchHeightAction), "Höhe übernehmen" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Schieben: von der Kamera weg" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Verschiebt die Auswahl in kleinen Schritten von der Kamera weg." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Schieben: zur Kamera hin" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Verschiebt die Auswahl in kleinen Schritten zur Kamera hin." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Schieben: nach links" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Verschiebt die Auswahl in kleinen Schritten nach links." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Schieben: nach rechts" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Verschiebt die Auswahl in kleinen Schritten nach rechts." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Ausricht-Abstand +" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Vergrößert den Abstand der letzten Ausrichtung (Line, To prop oder Circle) um 0,5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Ausricht-Abstand -" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Verkleinert den Abstand der letzten Ausrichtung (Line, To prop oder Circle) um 0,5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Anarchy beim Einfügen" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Ignoriert Platzierungsfehler (Überlappungen, Kollisionen) beim Einfügen — Objekte lassen sich überall platzieren, wie mit dem Anarchy-Mod." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kToggleAction), "Copaste-Werkzeug ein/aus" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kCopyAction), "Auswahl kopieren" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kPasteAction), "Einfügen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kDeleteAction), "Auswahl löschen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRaiseAction), "Auswahl anheben" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kLowerAction), "Auswahl absenken" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kUndoAction), "Rückgängig" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRedoAction), "Wiederholen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRelocateAction), "Gebäude versetzen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSelectSameAction), "Gleiche auswählen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSnapGroundAction), "Auf Gelände absetzen" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeUpAction), "Schieben: von der Kamera weg" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeDownAction), "Schieben: zur Kamera hin" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeLeftAction), "Schieben: nach links" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeRightAction), "Schieben: nach rechts" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapPlusAction), "Ausricht-Abstand +" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapMinusAction), "Ausricht-Abstand -" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kGeneralTab), "Allgemein" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kKeybindingsTab), "Tastenbelegung" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kBehaviorGroup), "Verhalten" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kToolGroup), "Werkzeug" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kClipboardGroup), "Zwischenablage" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kEditingGroup), "Bearbeiten" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kNudgeGroup), "Feinverschiebung" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kAlignGroup), "Ausrichten" },
                { settings.GetBindingMapLocaleID(), "Copaste" },
            };
        }

        internal static Dictionary<string, string> BuildFrench(CopasteSettings settings)
        {
            return new Dictionary<string, string>
            {
                { settings.GetSettingsLocaleID(), "Copaste" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ToggleBinding)), "Activer/désactiver l'outil Copaste" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ToggleBinding)), "Active ou désactive l'outil de sélection Copaste." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.CopyBinding)), "Copier la sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.CopyBinding)), "Copie les objets sélectionnés dans le presse-papiers (quand l'outil est actif)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PasteBinding)), "Coller" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PasteBinding)), "Passe en mode collage avec un aperçu qui suit la souris (quand l'outil est actif)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.DeleteBinding)), "Supprimer la sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.DeleteBinding)), "Supprime les objets sélectionnés (quand l'outil est actif)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RaiseBinding)), "Élever la sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RaiseBinding)), "Élève les objets sélectionnés (ou l'aperçu de collage) tant que la touche est maintenue." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.LowerBinding)), "Abaisser la sélection" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.LowerBinding)), "Abaisse les objets sélectionnés (ou l'aperçu de collage) tant que la touche est maintenue." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.UndoBinding)), "Annuler" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.UndoBinding)), "Annule la dernière action Copaste (déplacement, rotation, hauteur, suppression, collage)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RedoBinding)), "Rétablir" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RedoBinding)), "Rétablit la dernière action Copaste annulée (déplacement, rotation, alignement, hauteur, suppression, collage)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RelocateBinding)), "Déplacer le bâtiment" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RelocateBinding)), "Lance le déplacement du bâtiment sélectionné (exactement un bâtiment terminé sélectionné). Appuyez à nouveau ou clic droit pour annuler." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Sélectionner identiques" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Active un filtre de type (pris sur l'objet survolé/sélectionné) : tant qu'il est actif, la sélection au cadre ne prend que ce type. Appuyez à nouveau pour l'effacer." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Poser au sol" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Repose la sélection sur le terrain (réinitialise la hauteur)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Reprendre la hauteur" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Arme le choix de hauteur : le prochain objet cliqué définit la hauteur de toute la sélection." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kMatchHeightAction), "Reprendre la hauteur" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Décaler : loin de la caméra" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Décale légèrement la sélection en s'éloignant de la caméra." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Décaler : vers la caméra" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Décale légèrement la sélection vers la caméra." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Décaler : à gauche" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Décale légèrement la sélection vers la gauche." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Décaler : à droite" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Décale légèrement la sélection vers la droite." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Espacement d'alignement +" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Augmente de 0,5 m l'espacement du dernier alignement (Line, To prop ou Circle)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Espacement d'alignement -" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Réduit de 0,5 m l'espacement du dernier alignement (Line, To prop ou Circle)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Anarchy au collage" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Ignore les erreurs de placement (chevauchements, collisions) au collage — les objets peuvent être placés n'importe où, comme avec le mod Anarchy." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kToggleAction), "Activer/désactiver l'outil Copaste" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kCopyAction), "Copier la sélection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kPasteAction), "Coller" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kDeleteAction), "Supprimer la sélection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRaiseAction), "Élever la sélection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kLowerAction), "Abaisser la sélection" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kUndoAction), "Annuler" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRedoAction), "Rétablir" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRelocateAction), "Déplacer le bâtiment" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSelectSameAction), "Sélectionner identiques" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSnapGroundAction), "Poser au sol" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeUpAction), "Décaler : loin de la caméra" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeDownAction), "Décaler : vers la caméra" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeLeftAction), "Décaler : à gauche" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeRightAction), "Décaler : à droite" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapPlusAction), "Espacement d'alignement +" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapMinusAction), "Espacement d'alignement -" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kGeneralTab), "Général" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kKeybindingsTab), "Raccourcis clavier" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kBehaviorGroup), "Comportement" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kToolGroup), "Outil" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kClipboardGroup), "Presse-papiers" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kEditingGroup), "Édition" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kNudgeGroup), "Décalage fin" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kAlignGroup), "Alignement" },
                { settings.GetBindingMapLocaleID(), "Copaste" },
            };
        }

        internal static Dictionary<string, string> BuildSerbian(CopasteSettings settings)
        {
            return new Dictionary<string, string>
            {
                { settings.GetSettingsLocaleID(), "Copaste" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.ToggleBinding)), "Uključi/isključi Copaste alat" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.ToggleBinding)), "Aktivira/deaktivira Copaste alat za selekciju." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.CopyBinding)), "Kopiraj selekciju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.CopyBinding)), "Kopira selektovane propove u clipboard (dok je alat aktivan)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.PasteBinding)), "Nalepi" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.PasteBinding)), "Ulazi u paste mod sa preview-om koji prati miš (dok je alat aktivan)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.DeleteBinding)), "Obriši selekciju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.DeleteBinding)), "Briše selektovane propove (dok je alat aktivan)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RaiseBinding)), "Podigni selekciju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RaiseBinding)), "Podiže selektovane propove (ili paste preview) dok je taster pritisnut." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.LowerBinding)), "Spusti selekciju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.LowerBinding)), "Spušta selektovane propove (ili paste preview) dok je taster pritisnut." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.UndoBinding)), "Poništi (Undo)" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RedoBinding)), "Ponovi (Redo)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RedoBinding)), "Ponavlja poslednju poništenu Copaste akciju (pomeranje, rotacija, poravnanje, visina, brisanje, lepljenje)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.RelocateBinding)), "Premesti zgradu (Relocate)" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.RelocateBinding)), "Pokreće premeštanje selektovane zgrade (tačno jedna završena zgrada u selekciji). Ponovni pritisak ili desni klik odustaje." },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.UndoBinding)), "Poništava poslednju Copaste akciju (pomeranje, rotaciju, visinu, brisanje, lepljenje)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Selektuj iste" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SelectSameBinding)), "Uključuje filter tipa (uzet od propa pod mišem/selektovanog): dok je aktivan, marquee hvata samo taj tip. Ponovni pritisak gasi filter." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Spusti na teren" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.SnapGroundBinding)), "Vraća selekciju na visinu terena (resetuje visinu)." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Preuzmi visinu" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.MatchHeightBinding)), "Aktivira biranje visine: sledeći prop na koji klikneš zadaje visinu celoj selekciji." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kMatchHeightAction), "Preuzmi visinu" },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Pomak od kamere" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeUpBinding)), "Fino pomera selekciju od kamere." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Pomak ka kameri" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeDownBinding)), "Fino pomera selekciju ka kameri." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Pomak levo" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeLeftBinding)), "Fino pomera selekciju ulevo." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Pomak desno" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.NudgeRightBinding)), "Fino pomera selekciju udesno." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Align razmak +" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapPlusBinding)), "Povećava razmak poslednjeg poravnanja (Line, To prop ili Circle) za 0,5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Align razmak -" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AlignGapMinusBinding)), "Smanjuje razmak poslednjeg poravnanja (Line, To prop ili Circle) za 0,5 m." },
                { settings.GetOptionLabelLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Anarchy pri lepljenju" },
                { settings.GetOptionDescLocaleID(nameof(CopasteSettings.AnarchyPaste)), "Ignoriše greške postavljanja (preklapanja, kolizije) pri lepljenju — kao Anarchy mod." },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kToggleAction), "Uključi/isključi Copaste alat" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kCopyAction), "Kopiraj selekciju" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kPasteAction), "Nalepi" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kDeleteAction), "Obriši selekciju" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRaiseAction), "Podigni selekciju" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kLowerAction), "Spusti selekciju" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kUndoAction), "Poništi (Undo)" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRedoAction), "Ponovi (Redo)" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kRelocateAction), "Premesti zgradu (Relocate)" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSelectSameAction), "Selektuj iste" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kSnapGroundAction), "Spusti na teren" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeUpAction), "Pomak od kamere" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeDownAction), "Pomak ka kameri" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeLeftAction), "Pomak levo" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kNudgeRightAction), "Pomak desno" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapPlusAction), "Align razmak +" },
                { settings.GetBindingKeyLocaleID(CopasteSettings.kAlignGapMinusAction), "Align razmak -" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kGeneralTab), "Opšte" },
                { settings.GetOptionTabLocaleID(CopasteSettings.kKeybindingsTab), "Prečice" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kBehaviorGroup), "Ponašanje" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kToolGroup), "Alat" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kClipboardGroup), "Clipboard" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kEditingGroup), "Uređivanje" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kNudgeGroup), "Fini pomak" },
                { settings.GetOptionGroupLocaleID(CopasteSettings.kAlignGroup), "Poravnanje" },
                { settings.GetBindingMapLocaleID(), "Copaste" },
            };
        }
    }
}
